name: Morning Brief Automation

on:
  schedule:
    # Runs at 6:00 AM UTC (7:00 AM Europe/Berlin during standard time)
    # Adjust to 5:00 AM UTC during daylight saving time
    - cron: '0 6 * * *'
  
  # Allow manual trigger for testing
  workflow_dispatch:

jobs:
  send-morning-brief:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    
    - name: Run morning brief
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        TWITTER_BEARER_TOKEN: ${{ secrets.TWITTER_BEARER_TOKEN }}
        COINGECKO_PRO_API_KEY: ${{ secrets.COINGECKO_PRO_API_KEY }}
        TIMEZONE: Europe/Berlin
      run: |
        python morning_brief.py
    
    - name: Notify on failure
      if: failure()
      run: |
        echo "Morning brief failed to run"
